const LABELS = {
    iakpress: "IAKPress",
    all: "All",
    yes: "Yes",
    no: "No",
    ok: "OK",
    from: "From",
    to: "To",
    cc: "CC",
    bcc: "BCC",
    attachments: "Attachment(s)",
    general: "General",
    generalSettings: "General Settings",
    postElements: "Post Elements",
    slug: "Slug",
    slugName: "Slug Name",
    postSlugHelp: "The Post's Slug is used in the url when linking to a post.",
    fieldSlugHelp: "The Field's Slug is used in the form data when posting data to the server.",
    slugHelp: "Your Slug must begin with a letter, and can only contain alphanumeric characters and underscores.",
    nameHelp: "Name cannot exceed 32 characters",
    media: "Media",
    mediaLibrary: "Media Library",
    addNewMedia: "Add New Media File",
    desc: "Description",
    validation: "Validation",
    style: "Style",
    test: "Test",
    close: "close",
    delete: "Delete",
    cancel: "Cancel",
    prev: "Previous",
    title: "Title",
    date: "Date",
    actions: "Actions",
    submitLabel: "Submit",
    submit: "Save",
    addNewMediaFile: "Add New Media File",
    uploadMediaFile: "Chose a file or drag it here",
    uploadingMsg: "Uploading and pre-processing, please wait.",
    newPost: "New Post",
    getStarted: "Get Started",
    save: "Save",
    discard: "Discard",
    or: "OR",
    pay: "Pay",
    create: "Create",
    edit: "Edit",
    view: "View",
    add: "Add",
    manage: "Manage",
    home: "Home",
    back: "Back",
    select: "Select",
    group: "Group",
    subgroup: "Subgroup",
    step: "Step",
    import: "Import",
    export: "Export",
    preview: "Preview",
    publish: "Publish",
    unpublish: "Unpublish",
    published: "Published",
    unpublished: "Unpublished",
    dashboard: "Dashboard",
    fieldElementProps: "Field styling",
    publishSucceeded: "Publish Succeeded",
    delSucceeded: "Deletion Succeeded",
    defaultMenuItem: "Default Menu Item",
    menuItems: "Menu Items",
    frontendController: 'Frontend Controller',
    backendController: 'Backend Controller',
    logo: "Logo",
    logoImage: "Logo Image",
    headerImage: "Banner Image",
    backgroundImage: "Background Image",
    heroImage: "Hero Image",
    bodyStyling: "Body",
    formSettings: "Form Settings",
    formBuilder: "Form Builder",
    postSettings: "Post Settings",
    formBuild: "Form Build",
    settings: "Settings",
    advancedSettings: "Advanced Settings",
    fieldList: "Field List",
    users: "Users",
    fields: "Fields",
    products: "Products",
    requiredField: "This field is required.",
    invalidFormat: "Invalid format.",
    fieldValueTooLong: "Data too long for field (max length : %s Characters)",
    fieldValueTooShort: "Data too short for field (min length : %s Characters)",
    minLenBefore: " Oops! You need to enter at least",
    minLenAfter: "characters.",
    maxLenBefore: "Oops! You can only enter",
    maxLenAfter: "characters.",
    invalidFieldValue: "The field value is invalid.",
    build: "Build",
    page: "Page",
    pages: "Pages",
    sections: "Sections",
    newSection: "New Section",
    section: "Section",
    apply: "Apply",
    length: "Length",
    width: "Width",
    height: "Height",
    visual: "Visual",
    form: "Form",
    post: "Post",
    reset: "Reset",
    continue: "Continue",
    rprice: "Regular price",
    posts: "Posts",
    apps: "Apps",
    footer: "Footer",
    header: "Header",
    submitBtn: "Submit Button",
    submitBtnLabel: "Submit Button Label",
    nextBtn: "Next Button",
    prevBtn: "Previous Button",
    nextBtnLabel: "Next Button Label",
    prevBtnLabel: "Previous Button Label",
    navBar: "Navigation",
    formSubmit: "Form Submit",
    submitErrorMsg: "Submit Error Message",
    submitSuccessMsg: "Submit Success Message",
    menu: "Menu",
    subject: "Subject",
    send: "Send",
    next: "Next",
    label: "Label",
    text: "Text",
    email: "Email",
    phone: "Phone number",
    password: "Password",
    firstname: "First name",
    lastname: "Last name",
    name: "Name",
    forms: "Forms",
    message: "Message",
    smtp: "SMTP",
    paypal: "PayPal",
    braintree: "Braintree",
    stripe: "Stripe",
    ecommerce: "E-commerce",
    left: "Left",
    right: "Right",
    username: "Username",
    timezone: "Timezone",
    product: "Product",
    price: "Price",
    quantity: "Quantity",
    entries: "Entries",
    appearance: "Appearance",
    archivepage: "Archive Page",
    singlepage: "Single Page",
    choices: "Choices",
    choiceGroups: "Choice Groups",
    newChoice: "New Choice",
    option: "Option",
    views: "Views",
    reports: "Reports",
    attrgroup: "Attribute Group",
    field: "Field",
    datatable: "Data Table",
    requestform: "Request Form",
    searchform: "Search Form",
    orderform: "Order Form",
    displaytpl: "Display Template",
    datamodel: "Data Model",
    fieldSettings: "Field Settings",
    addFields: "Add Fields",
    newField: "New Field",
    newForm: "New Form",
    billing: "Billing",
    plan: "Plan",
    type: "Type",
    download: "Download",
    elements: "Elements",
    styling: "Styling",
    pricing: "Pricing",
    invalidEmail: "Invalid Email",
    invalidPassword: "Invalid Password",
    userInfo: "User Information",
    createAccountTitle: "Create your IAKPress account",
    verificationCode: "Verification code",
    resetCodeTitle: "Send password reset code",
    resetCodeSubtitle: "We'll send a 6-digit code to your email.",
    createAccountSubtitle: "Don't lose access to your posts by creating an IAKPress account.",
    signupPrivacyTitle: "By clicking 'Sign up', you agree to our",
    signupPrivacySubtitle: "Terms & Privacy Policy",
    cantLogIn: "Can't Log In?",
    notHaveAccount: "Don't have an account ?",
    signUp: "Sign up",
    haveAccount: "Already have an account ?",
    logIn: "Log in",
    logOut: "Log out",
    signIn: "Sign in",
    welcomeBack: "Welcome back",
    emailOrPhone: "Email",
    changePassword: "Change password",
    resetPassword: "Reset password",
    forgotPassword: "Forgot your password ?",
    unknownError: "An unknown error has occured.",
    userExists: "A user with that email already exists",
    wrongCredentials: "Wrong Credentials",
    createNew: "Create new",
    uploadImage: "Upload Image",
    addNewField: "Add New Field",
    dragAndDropField: "Drag and Drop a form component",
    contactform: 'Contact Form',
    contactformDesc: 'Receive messages from your website visitors.',
    advancedform: 'Advanced Form',
    advancedformDesc: 'Create a new form from scratch.',
    onlinestore: 'Online Store',
    onlinestoreDesc: 'Build a product list in minutes and start sell your products.',
    multistepform: 'Multi-Step Form',
    multistepformDesc: 'Create a form with multiple steps.',
};

export default LABELS;